---
name: End-to-end tests
on: [push]
env: # Comment env block if you do not want to apply fixes
  # JSONBIN access vars
  VUE_APP_JSONBIN_X_ACCESS_KEY: \$2b\$10\$/gwhSdy2//J8hW7MYV1ZQOPQeLg4obm1QuKQcSPwvDAQx034GZqRu
  VUE_APP_JSONBIN_CERTIFIICATES_ID: 636db99f2b3499323bfc386a
  VUE_APP_JSONBIN_PROJECTS_ID: 636db9412b3499323bfc3829
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Download the build folders
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: build
      #     path: build

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          node-version: 16
          install-command: yarn
          build: yarn build
          # start: npx serve -s dist -l 8080
          start: npm run serve
          browser: chrome
          headed: false
          headless: true
          # browser: firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
